### PR TITLE
chore: TS base

### PR DESCRIPTION
**Pull request by vladfrangu**

### CODE REVIEW

**Comment by vladfrangu** [comment]
CC: @pocesar @B4nan

I forgot to put it in the body of the PR, sorry 😓

**Review by B4nan — CHANGES_REQUESTED** [review]
Looks good, but the CI is failing on windows, I guess some `/` vs `\` issue in paths/jest setup?

**Comment by vladfrangu** [comment]
> Looks good, but the CI is failing on windows, I guess some `/` vs `\` issue in paths/jest setup?

Yeah, that is...weird, considering it worked fine for storage-local... Anywho, fixed

**Comment by B4nan** [comment]
It's actually also commented there :D 

https://github.com/apify/apify-storage-local-js/blob/master/jest.config.ts#L9

**Comment by B4nan** [comment]
Something is still wrong in there, some tests are executed, and pass, but the build got stuck without any errors:

https://github.com/apify/browser-pool/pull/30/checks?check_run_id=2436401043

Comparing to the linux builds, some tests were not executed in the windows one. I did cancel the build after few minutes as there were no visible updates, but I don't think this is "wait few more minutes and it will pass" problem :D

**Comment by vladfrangu** [comment]
Well, the tests took 69 seconds on my local PC to execute, the entire time being taken by ` PASS  test/browser-plugins/plugins.test.js (68.029 s)`. I think this is a case of the CI env being too slow... unless it was fast before this PR?

**Comment by B4nan** [comment]
I see, you are probably right, the tests were slow as hell on windows before (~12 minutes to pass). Will restart the build and lets wait a bit more.

https://github.com/apify/browser-pool/runs/2143312068?check_suite_focus=true

**Comment by vladfrangu** [comment]
gee, this CI hates me.. Can we get a re-run? 😓

**Review by B4nan — APPROVED** [review]

**Comment by B4nan** [comment]
I guess this is ready to be merged, cc @mnmkng

(btw regular reminder that it would be great to change the default to squash merging :])

**Comment by mnmkng** [comment]
@vladfrangu Before I merge it, could you please bump the version to `1.2.0` and update the changelog? We usually use `NEXT` instead of the date there, until the version is released. A short mention that we updated to TypeScript would be enough.

**Review by mnmkng — APPROVED** [review]

**Comment by B4nan** [comment]
The build is failing, and I'd say this is again due to the wrong caching, without lock file, we can't invalidate the NPM cache (this problem is only when re-running the failed builds, as the cache key uses the same run id).

**Comment by vladfrangu** [comment]
> The build is failing, and I'd say this is again due to the wrong caching, without lock file, we can't invalidate the NPM cache (this problem is only when re-running the failed builds, as the cache key uses the same run id).

Triggered CI again, it passed \o/

**Comment by B4nan** [comment]
Yop, because the run id changed. We had the same issue in other repository that used the same caching mechanism. 

Will repeat myself, but for me the solution is to add lock files to git and invalidate cache based on it. It will allow proper caching of all node modules, across builds (unless we change some dependencies).

**Comment by mnmkng** [comment]
@B4nan In the SDK check workflow we removed the cache completely and I think it works fine. We can remove it here too. I'm still reluctant to use package lock without dependency pinning.

**Pull request merged**
